def addRangeToTable(probability, item, table):
    for i in range (probability):
        table.append(item)


tableA = []
addRangeToTable(50,"potion of healing",tableA)
addRangeToTable(10,"spell scroll (cantrip)",tableA)
addRangeToTable(10,"potion of climbing",tableA)
addRangeToTable(20,"spell scroll (level 1)",tableA)
addRangeToTable(4,"spell scroll (level 2)",tableA)
addRangeToTable(4,"potion of greater healing",tableA)
addRangeToTable(1,"bag of holding",tableA)
addRangeToTable(1,"driftglobe",tableA)

tableB = []
addRangeToTable(15,"Potion of greater healing",tableB)
addRangeToTable(7,"potion of fire breath",tableB)
addRangeToTable(7,"potion of resistance",tableB)
addRangeToTable(5,"Ammunition, +1",tableB)
addRangeToTable(5,"potion of animal friendship",tableB)
addRangeToTable(5,"potion of hill giant strength",tableB)
addRangeToTable(5,"potion of growth",tableB)
addRangeToTable(5,"potion of water breathing",tableB)
addRangeToTable(5,"spell scroll (level 2)",tableB)
addRangeToTable(5,"spell scroll (level 3)",tableB)
addRangeToTable(3,"bag of holding",tableB)
addRangeToTable(3,"keoghtom's ointment",tableB)
addRangeToTable(3,"oil of slipperiness",tableB)
addRangeToTable(2,"dust of disapperance",tableB)
addRangeToTable(2,"dust of dryness",tableB)
addRangeToTable(2,"dust of sneezing and choking",tableB)
addRangeToTable(2,"elemental gem",tableB)
addRangeToTable(2,"philter of love",tableB)
addRangeToTable(1,"Alchemy Jug",tableB)
addRangeToTable(1,"Cap of water breathing",tableB)
addRangeToTable(1,"Cloak of the manta ray",tableB)
addRangeToTable(1,"driftglobe",tableB)
addRangeToTable(1,"goggles of night",tableB)
addRangeToTable(1,"helm of comprehending language",tableB)
addRangeToTable(1,"immovable rod",tableB)
addRangeToTable(1,"Lantern of revealing",tableB)
addRangeToTable(1,"Mariner's armor",tableB)
addRangeToTable(1,"Mithral armor",tableB)
addRangeToTable(1,"Potion of poison",tableB)
addRangeToTable(1,"Ring of swimming",tableB)
addRangeToTable(1,"Robe of usefull items",tableB)
addRangeToTable(1,"Rope of climbing",tableB)
addRangeToTable(1,"Saddle of cavalier",tableB)
addRangeToTable(1,"wand of magic detection",tableB)
addRangeToTable(1,"wand of secrets",tableB)

tableC = []
addRangeToTable(15,"Potion of superior healing",tableC)
addRangeToTable(7,"Spell Scroll (4th level)",tableC)
addRangeToTable(7,"Ammunition, +2",tableC)
addRangeToTable(5,"potion of clairvoyance",tableC)
addRangeToTable(5,"potion of diminution",tableC)
addRangeToTable(5,"potion of gaseous form",tableC)
addRangeToTable(5,"potion of frost giant strength",tableC)
addRangeToTable(5,"potion of stone giant strength",tableC)
addRangeToTable(5,"potion of heroism",tableC)
addRangeToTable(5,"potion of invulnerability",tableC)
addRangeToTable(5,"potion of mind reading",tableC)
addRangeToTable(3,"spell scroll(5th level)",tableC)
addRangeToTable(3,"elixir of health",tableC)
addRangeToTable(3,"oil of etherealness",tableC)
addRangeToTable(3,"potion of fire giant strength",tableC)
addRangeToTable(3,"Quaal's feather token",tableC)
addRangeToTable(3,"Scroll of protection",tableC)
addRangeToTable(2,"Bag of beans",tableC)
addRangeToTable(2,"Bead of force",tableC)
addRangeToTable(1,"chime of opening",tableC)
addRangeToTable(1,"Decanter of endless water",tableC)
addRangeToTable(1,"Eye of minute seeing",tableC)
addRangeToTable(1,"Folding boat",tableC)
addRangeToTable(1,"Heward's handy haversack",tableC)
addRangeToTable(1,"Horseshoes of speed",tableC)
addRangeToTable(1,"Necklace of fireballs",tableC)
addRangeToTable(1,"Periapt of health",tableC)
addRangeToTable(1,"Sending stones",tableC)

tableD = []
addRangeToTable(20,"Potion of supreme healing",tableD)
addRangeToTable(10,"Potion of invisibility",tableD)
addRangeToTable(10,"Potion of speed",tableD)
addRangeToTable(10,"spell scroll(6th level)",tableD)
addRangeToTable(7,"spell scroll(7th level)",tableD)
addRangeToTable(5,"Ammunition, +3",tableD)
addRangeToTable(5,"oil of sharpness",tableD)
addRangeToTable(5,"potion of flying",tableD)
addRangeToTable(5,"Potion of cloud giant strength",tableD)
addRangeToTable(5,"Potion of longevity",tableD)
addRangeToTable(5,"Potion of vitality",tableD)
addRangeToTable(5,"spell scroll(8th level)",tableD)
addRangeToTable(3,"Horseshoes of a zephyr",tableD)
addRangeToTable(3,"Nolzur's mrvelous pigments",tableD)
addRangeToTable(1,"Bag of devouring",tableD)
addRangeToTable(1,"portable hole",tableD)

tableE = []
addRangeToTable(30,"Spell scroll (8th level)",tableE)
addRangeToTable(25,"Potion of storm giant strength",tableE)
addRangeToTable(15,"Potion of healing (supreme)",tableE)
addRangeToTable(15,"Spell scroll (9th level)",tableE)
addRangeToTable(8,"Universal solvent",tableE)
addRangeToTable(5,"Arrow of slaying",tableE)
addRangeToTable(2,"Sovereign glue",tableE)

tableF = []
addRangeToTable(15,"Weapon, +1",tableF)
addRangeToTable(3,"Shield, +1", tableF)
addRangeToTable(3,"Sentinel shield", tableF)
addRangeToTable(2, "Amulet of proof against detection and location", tableF)
addRangeToTable(2, "Boots of elvenkind", tableF)
addRangeToTable(2, "Boots of striding and springing", tableF)
addRangeToTable(2, "Boots of archery", tableF)
addRangeToTable(2,"Brooch of shielding", tableF)
addRangeToTable(2, "Broom of flying", tableF)
addRangeToTable(2, "Cloak of elvenkind", tableF)
addRangeToTable(2, "Cloak of protection", tableF)
addRangeToTable(2, "Gauntlents of ogre power", tableF)
addRangeToTable(2, "Hat of disguise", tableF)
addRangeToTable(2, "Javelin of lightning", tableF)
addRangeToTable(2, "Pearl of power", tableF)
addRangeToTable(2, "Rod of the pact keeper, +1", tableF)
addRangeToTable(2, "Slippers of spider climbing", tableF)
addRangeToTable(2, "Staff of the adder", tableF)
addRangeToTable(2, "Staff of the python", tableF)
addRangeToTable(2, "Sword of vengeance", tableF)
addRangeToTable(2, "Trident of fish command", tableF)
addRangeToTable(2, "Wand of magic missiles", tableF)
addRangeToTable(2, "Wand of the war mage, +1", tableF)
addRangeToTable(2, "Wand of web", tableF)
addRangeToTable(2, "Weapon of warning", tableF)
addRangeToTable(1, "Adamantine armor (chain mail)", tableF)
addRangeToTable(1, "Adamantine armor (chain shirt)", tableF)
addRangeToTable(1, "Adamantine armor (scale mail)", tableF)
addRangeToTable(1, "Bag of tricks (gray)", tableF)
addRangeToTable(1, "Bag of tricks (rust)", tableF)
addRangeToTable(1, "Bag of tricks (tan)", tableF)
addRangeToTable(1, "Boots of the winterlands", tableF)
addRangeToTable(1, "Circlet of blasting", tableF)
addRangeToTable(1, "Deck of illusions", tableF)
addRangeToTable(1, "Eversmoking bottle", tableF)
addRangeToTable(1, "Eyes of charming", tableF)
addRangeToTable(1, "Eyes of the eagle", tableF)
addRangeToTable(1, "Figurine of wondrous power (silver raven)", tableF)
addRangeToTable(1, "Gem of brightness", tableF)
addRangeToTable(1, "Gloves of missile snaring", tableF)
addRangeToTable(1, "Gloves of swimming and climbing", tableF)
addRangeToTable(1, "Gloves of thievery", tableF)
addRangeToTable(1, "Headband of intellect", tableF)
addRangeToTable(1, "Helm of telepathy", tableF)
addRangeToTable(1, "Instrument of the bards (Doss lute)", tableF)
addRangeToTable(1, "Instrument of the bards (Fochlucan bandore)", tableF)
addRangeToTable(1, "Instrument of the bards (Mac-Fuimidh cittern)", tableF)
addRangeToTable(1, "Medallion of thoughts", tableF)
addRangeToTable(1, "Necklace of adaptation", tableF)
addRangeToTable(1, "Periapt of wound closure", tableF)
addRangeToTable(1, "Pipes of haunting", tableF)
addRangeToTable(1, "Pipes of the sewers", tableF)
addRangeToTable(1, "Ring of jumping", tableF)
addRangeToTable(1, "Ring of mind shielding", tableF)
addRangeToTable(1, "Ring of warmth", tableF)
addRangeToTable(1, "Ring of water walking", tableF)
addRangeToTable(1, "Quiver of Ehlonna", tableF)
addRangeToTable(1, "Stone of good luck (luckstone)", tableF)
addRangeToTable(1, "Wind fan", tableF)
addRangeToTable(1, "Winged boots", tableF)

tableG = []
addRangeToTable(11, "Weapon, +2", tableG)
addRangeToTable(3,"Figurune of wonderous power (roll d8) - 1 Figurine of wondrous power (Bronze griffon)\n2 Figurine of wondrous power (Ebony fly)\n3 Figurine of wondrous power (Golden lions)\n4 Figurine of wondrous power (Ivory goats)\n5 Figurine of wondrous power (Marble elephant)\n6–7 Figurine of wondrous power (Onyx dog)\n8 Figurine of wondrous power (Serpentine owl)", tableG)
addRangeToTable(1,"Adamantine armor (breastplate)",tableG)
addRangeToTable(1,"Adamantine armor (splint)",tableG)
addRangeToTable(1,"Amulet of health",tableG)
addRangeToTable(1,"Armor of vulnerability",tableG)
addRangeToTable(1,"Arrow-catching shield",tableG)
addRangeToTable(1,"Belt of dwarvenkind",tableG)
addRangeToTable(1,"Belt of hill giant strength",tableG)
addRangeToTable(1,"Berserker axe",tableG)
addRangeToTable(1,"Boots of levitation",tableG)
addRangeToTable(1,"Boots of speed",tableG)
addRangeToTable(1,"Bowl of commanding water elementals",tableG)
addRangeToTable(1,"Bracers of defense",tableG)
addRangeToTable(1,"Brazier of commanding fire elementals",tableG)
addRangeToTable(1,"Cape of the mountebank",tableG)
addRangeToTable(1,"Censer of controlling air elementals",tableG)
addRangeToTable(1,"Armor, +1 chain mail",tableG)
addRangeToTable(1,"Armor of resistance (chain mail)",tableG)
addRangeToTable(1,"Armor, +1 chain shirt",tableG)
addRangeToTable(1,"Armor of resistance (chain shirt)",tableG)
addRangeToTable(1,"Cloak of displacement",tableG)
addRangeToTable(1,"Cloak of the bat",tableG)
addRangeToTable(1,"Cube of force",tableG)
addRangeToTable(1,"Daern’s instant fortress",tableG)
addRangeToTable(1,"Dagger of venom",tableG)
addRangeToTable(1,"Dimensional shackles",tableG)
addRangeToTable(1,"Dragon slayer",tableG)
addRangeToTable(1,"Elven chain",tableG)
addRangeToTable(1,"Flame tongue",tableG)
addRangeToTable(1,"Gem of seeing",tableG)
addRangeToTable(1,"Giant slayer",tableG)
addRangeToTable(1,"Glamoured studded leather",tableG)
addRangeToTable(1,"Helm of teleportation",tableG)
addRangeToTable(1,"Horn of blasting",tableG)
addRangeToTable(1,"Horn of Valhalla (silver or brass)",tableG)
addRangeToTable(1,"Instrument of the bards (Canaith mandolin)",tableG)
addRangeToTable(1,"Instrument of the bards (Cli lyre)",tableG)
addRangeToTable(1,"Ioun stone (awareness)",tableG)
addRangeToTable(1,"Ioun stone (protection)",tableG)
addRangeToTable(1,"Ioun stone (reserve)",tableG)
addRangeToTable(1,"Ioun stone (sustenance)",tableG)
addRangeToTable(1,"Iron bands of Bilarro",tableG)
addRangeToTable(1,"Armor, +1 leather",tableG)
addRangeToTable(1,"Armor of resistance (leather)",tableG)
addRangeToTable(1,"Mace of disruption",tableG)
addRangeToTable(1,"Mace of smiting",tableG)
addRangeToTable(1,"Mace of terror",tableG)
addRangeToTable(1,"Mantle of spell resistance",tableG)
addRangeToTable(1,"Necklace of prayer beads",tableG)
addRangeToTable(1,"Periapt of proof against poison",tableG)
addRangeToTable(1,"Ring of animal influence",tableG)
addRangeToTable(1,"Ring of evasion",tableG)
addRangeToTable(1,"Ring of feather falling",tableG)
addRangeToTable(1,"Ring of free action",tableG)
addRangeToTable(1,"Ring of protection",tableG)
addRangeToTable(1,"Ring of resistance",tableG)
addRangeToTable(1,"Ring of spell storing",tableG)
addRangeToTable(1,"Ring of the ram",tableG)
addRangeToTable(1,"Ring of X-ray vision",tableG)
addRangeToTable(1,"Robe of eyes",tableG)
addRangeToTable(1,"Rod of rulership",tableG)
addRangeToTable(1,"Rod of the pact keeper, +2",tableG)
addRangeToTable(1,"Rope of entanglement",tableG)
addRangeToTable(1,"Armor, +1 scale mail",tableG)
addRangeToTable(1,"Armor of resistance (scale mail)",tableG)
addRangeToTable(1,"Shield, +2",tableG)
addRangeToTable(1,"Shield of missile attraction",tableG)
addRangeToTable(1,"Staff of charming",tableG)
addRangeToTable(1,"Staff of healing",tableG)
addRangeToTable(1,"Staff of swarming insects",tableG)
addRangeToTable(1,"Staff of the woodlands",tableG)
addRangeToTable(1,"Staff of withering",tableG)
addRangeToTable(1,"Stone of controlling earth elementals",tableG)
addRangeToTable(1,"Sun blade",tableG)
addRangeToTable(1,"Sword of life stealing",tableG)
addRangeToTable(1,"Sword of wounding",tableG)
addRangeToTable(1,"Tentacle rod",tableG)
addRangeToTable(1,"Vicious weapon",tableG)
addRangeToTable(1,"Wand of binding",tableG)
addRangeToTable(1,"Wand of enemy detection",tableG)
addRangeToTable(1,"Wand of fear",tableG)
addRangeToTable(1,"Wand of fireballs",tableG)
addRangeToTable(1,"Wand of lightning bolts",tableG)
addRangeToTable(1,"Wand of paralysis",tableG)
addRangeToTable(1,"Wand of the war mage, +2",tableG)
addRangeToTable(1,"Wand of wonder",tableG)
addRangeToTable(1,"Wings of flying",tableG)

tableH = []
addRangeToTable(10,"Weapon, +3",tableH)
addRangeToTable(2,"Amulet of the planes",tableH)
addRangeToTable(2,"Carpet of flying",tableH)
addRangeToTable(2,"Crystal ball (very rare version)",tableH)
addRangeToTable(2,"Ring of regeneration",tableH)
addRangeToTable(2,"Ring of shooting stars",tableH)
addRangeToTable(2,"Ring of telekinesis",tableH)
addRangeToTable(2,"Robe of scintillating colors",tableH)
addRangeToTable(2,"Robe of stars",tableH)
addRangeToTable(2,"Rod of absorption",tableH)
addRangeToTable(2,"Rod of alertness",tableH)
addRangeToTable(2,"Rod of security",tableH)
addRangeToTable(2,"Rod of the pact keeper, +3",tableH)
addRangeToTable(2,"Scimitar of speed",tableH)
addRangeToTable(2,"Shield, +3",tableH)
addRangeToTable(2,"Staff of fire",tableH)
addRangeToTable(2,"Staff of frost",tableH)
addRangeToTable(2,"Staff of power",tableH)
addRangeToTable(2,"Staff of striking",tableH)
addRangeToTable(2,"Staff of thunder and lightning",tableH)
addRangeToTable(2,"Sword of sharpness",tableH)
addRangeToTable(2,"Wand of polymorph",tableH)
addRangeToTable(2,"Wand of the war mage, +3",tableH)
addRangeToTable(1,"Adamantine armor (half plate)",tableH)
addRangeToTable(1,"Adamantine armor (plate)",tableH)
addRangeToTable(1,"Animated shield",tableH)
addRangeToTable(1,"Belt of fire giant strength",tableH)
addRangeToTable(1,"Belt of frost giant strength (or stone)",tableH)
addRangeToTable(1,"Armor, +1 breastplate",tableH)
addRangeToTable(1,"Armor of resistance (breastplate)",tableH)
addRangeToTable(1,"Candle of invocation",tableH)
addRangeToTable(1,"Armor, +2 chain mail",tableH)
addRangeToTable(1,"Armor, +2 chain shirt",tableH)
addRangeToTable(1,"Cloak of arachnida",tableH)
addRangeToTable(1,"Dancing sword",tableH)
addRangeToTable(1,"Demon armor",tableH)
addRangeToTable(1,"Dragon scale mail",tableH)
addRangeToTable(1,"Dwarven plate",tableH)
addRangeToTable(1,"Dwarven thrower",tableH)
addRangeToTable(1,"Efreeti bottle",tableH)
addRangeToTable(1,"Figurine of wondrous power (obsidian steed)",tableH)
addRangeToTable(1,"Frost brand",tableH)
addRangeToTable(1,"Helm of brilliance",tableH)
addRangeToTable(1,"Horn of Valhalla (bronze)",tableH)
addRangeToTable(1,"Instrument of the bards (Anstruth harp)",tableH)
addRangeToTable(1,"Ioun stone (absorption)",tableH)
addRangeToTable(1,"Ioun stone (agility)",tableH)
addRangeToTable(1,"Ioun stone (fortitude)",tableH)
addRangeToTable(1,"Ioun stone (insight)",tableH)
addRangeToTable(1,"Ioun stone (intellect)",tableH)
addRangeToTable(1,"Ioun stone (leadership)",tableH)
addRangeToTable(1,"Ioun stone (strength)",tableH)
addRangeToTable(1,"Armor, +2 leather",tableH)
addRangeToTable(1,"Manual of bodily health",tableH)
addRangeToTable(1,"Manual of gainful exercise",tableH)
addRangeToTable(1,"Manual of golems",tableH)
addRangeToTable(1,"Manual of quickness of action",tableH)
addRangeToTable(1,"Mirror of life trapping",tableH)
addRangeToTable(1,"Nine lives stealer",tableH)
addRangeToTable(1,"Oathbow",tableH)
addRangeToTable(1,"Armor, +2 scale mail",tableH)
addRangeToTable(1,"Spellguard shield",tableH)
addRangeToTable(1,"Armor, +1 splint",tableH)
addRangeToTable(1,"Armor of resistance (splint)",tableH)
addRangeToTable(1,"Armor, +1 studded leather",tableH)
addRangeToTable(1,"Armor of resistance (studded leather)",tableH)
addRangeToTable(1,"Tome of clear thought",tableH)
addRangeToTable(1,"Tome of leadership and influence",tableH)
addRangeToTable(1,"Tome of understanding",tableH)

tableI = []
addRangeToTable(5,"Defender",tableI)
addRangeToTable(5,"Hammer of thunderbolts",tableI)
addRangeToTable(5,"Luck blade",tableI)
addRangeToTable(5,"Sword of answering",tableI)
addRangeToTable(3,"Holy avenger",tableI)
addRangeToTable(3,"Ring of djinni summoning",tableI)
addRangeToTable(3,"Ring of invisibility",tableI)
addRangeToTable(3,"Ring of spell turning",tableI)
addRangeToTable(3,"Rod of lordly might",tableI)
addRangeToTable(3,"Staff of the magi",tableI)
addRangeToTable(3,"Vorpal sword",tableI)
addRangeToTable(2,"Belt of cloud giant strength",tableI)
addRangeToTable(2,"Armor, +2 breastplate",tableI)
addRangeToTable(2,"Armor, +3 chain mail",tableI)
addRangeToTable(2,"Armor, +3 chain shirt",tableI)
addRangeToTable(2,"Cloak of invisibility",tableI)
addRangeToTable(2,"Crystal ball (legendary version)",tableI)
addRangeToTable(2,"Armor, +1 half plate",tableI)
addRangeToTable(2,"Iron flask",tableI)
addRangeToTable(2,"Armor, +3 leather",tableI)
addRangeToTable(2,"Armor, +1 plate",tableI)
addRangeToTable(2,"Robe of the archmagi",tableI)
addRangeToTable(2,"Rod of resurrection",tableI)
addRangeToTable(2,"Armor, +1 scale mail",tableI)
addRangeToTable(2,"Scarab of protection",tableI)
addRangeToTable(2,"Armor, +2 splint",tableI)
addRangeToTable(2,"Armor, +2 studded leather",tableI)
addRangeToTable(2,"Well of many worlds",tableI)
addRangeToTable(1,"Magic armor (roll d12) - 1–2 Armor, +2 half plate \n 3–4 +2 plate \n 5–6 +3 studded leather \n 7–8 +3 breastplate \n 9–10 +3 splint \n 11 +3 half plate \n 12 +3 plate",tableI)
addRangeToTable(1,"Apparatus of Kwalish",tableI)
addRangeToTable(1,"Armor of invulnerability",tableI)
addRangeToTable(1,"Belt of storm giant strength",tableI)
addRangeToTable(1,"Cubic gate",tableI)
addRangeToTable(1,"Deck of many things",tableI)
addRangeToTable(1,"Efreeti chain",tableI)
addRangeToTable(1,"Armor of resistance (half plate)",tableI)
addRangeToTable(1,"Horn of Valhalla (iron)",tableI)
addRangeToTable(1,"Instrument of the bards (Ollamh harp)",tableI)
addRangeToTable(1,"Ioun stone (greater absorption)",tableI)
addRangeToTable(1,"Ioun stone (mastery)",tableI)
addRangeToTable(1,"Ioun stone (regeneration)",tableI)
addRangeToTable(1,"Plate armor of etherealness",tableI)
addRangeToTable(1,"Armor of resistance (plate)",tableI)
addRangeToTable(1,"Ring of air elemental command",tableI)
addRangeToTable(1,"Ring of earth elemental command",tableI)
addRangeToTable(1,"Ring of fire elemental command",tableI)
addRangeToTable(1,"Ring of three wishes",tableI)
addRangeToTable(1,"Ring of water elemental command",tableI)
addRangeToTable(1,"Sphere of annihilation",tableI)
addRangeToTable(1,"Talisman of pure good",tableI)
addRangeToTable(1,"Talisman of the sphere",tableI)
addRangeToTable(1,"Talisman of ultimate evil",tableI)
addRangeToTable(1,"Tome of the stilled tongue",tableI)

magicItems = {'A':tableA,'B':tableB,'C':tableC, 'D': tableD, 'E': tableE, 'F':tableF,'G': tableG, 'H': tableH, 'I': tableI }

artDescriptions={
    1:["terrible watercolor painting"],
    25:["Silver ewer","Carved bone statuette","Small gold bracelet","Cloth-of-gold vestments","Black velvet mask stitched with silver thread","Copper chalice with silver filigree","Pair of engraved bone dice","Small mirror set in a painted wooden frame","Embroidered silk handkerchief","Gold locket with a painted portrait inside"],
    250:["Gold ring set with bloodstones","Carved ivory statuette","Large gold bracelet","Silver necklace with a gemstone pendant","Bronze crown","Silk robe with gold embroidery","Large well-made tapestry","Brass mug with jade inlay","Box of turquoise animal figurines","Gold bird cage with electrum filigree"],
    750:["Silver chalice set with moonstones", "Silver-plated steel longsword with jet set in hilt", "Carved harp of exotic wood with ivory inlay and zircon gems", "Small gold idol", "Gold dragon comb set with red garnets as eyes", "Bottle stopper cork embossed with gold leaf and set with amethysts", "Ceremonial electrum dagger with a black pearl in the pommel", "Silver and gold brooch", "Obsidian statuette with gold fittings and inlay", "Painted gold war mask"],
    2500:["Fine gold chain set with a fire opal", "Old masterpiece painting", "Embroidered silk and velvet mantle set with numerous moonstones", "Platinum bracelet set with a sapphire", "Embroidered glove set with jewel chips", "Jeweled anklet", "Gold music box", "Gold circlet set with four aquamarines", "Eye patch with a mock eye set in blue sapphire and moonstone", "A necklace string of small pink pearls"],
    7500:["Jeweled gold crown", "Jeweled platinum ring", "Small gold statuette set with rubies", "Gold cup set with emeralds", "Gold jewelry box with platinum filigree", "Painted gold child’s sarcophagus", "Jade game board with solid gold playing pieces","Bejeweled ivory drinking horn with gold filigree"]}

gemDescriptions={
    1:["worthless rocks"],
    10:["Azurite","Banded agate","Blue quartz","Eye agate","Hematite","Lapis lazuli","Malachite","Moss agate","Obsidian","Rhodochrosite","Tiger eye","Turquoise"],
    50:["Bloodstone","Carnelian","Chalcedony","Chrysoprase","Citrine","Jasper","Moonstone","Onyx","Quartz","Sardonyx","Star rose quartz","Zircon"],
    100:["Amber","Amethyst","Chrysoberyl","Coral","Garnet","Jade","Jet","Pearl","Spinel","Tourmaline"],
    500:["Alexandrite","Aquamarine","Black pearl","Blue spinel","Peridot","Topaz"],
    1000:["Black opal","Blue sapphire","Emerald","Fire opal","Opal","Star ruby","Star sapphire","Yellow sapphire"],
    5000:["Black sapphire","Diamond","Jacinth","Ruby"]
}
individual = []
i0to4 = []
addRangeToTable(30, ['5d6', '0', '0', '0','0'], i0to4 )
addRangeToTable(30, ['0', '4d6', '0', '0','0'], i0to4 )
addRangeToTable(10, ['0', '0', '3d6', '0','0'], i0to4 )
addRangeToTable(25, ['0', '0', '0', '3d6','0'], i0to4 )
addRangeToTable(5, ['0', '0', '0', '0','1d6'], i0to4 )


i5to10 = []
addRangeToTable(30,['4d6x100', '0', '1d6x10', '0', '0'], i5to10 )
addRangeToTable(30,['0', '6d6x10', '0', '2d6x10', '0'], i5to10 )
addRangeToTable(10,['0', '0', '3d6x10', '2d6x10', '0'], i5to10 )
addRangeToTable(25,['0', '0', '0', '4d6x10','0'], i5to10 )
addRangeToTable(5, ['0', '0', '2d6x10', '3d6'], i5to10 )

i11to16 = []
addRangeToTable(20,['0', '4d6x100', '0', '1d6x10', '0'],i11to16)
addRangeToTable(15,['0', '0', '1d6x100', '1d6x100', '0'],i11to16)
addRangeToTable(40,['0', '0', '0', '2d6x100', '1d6x10'],i11to16)
addRangeToTable(25,['0', '0', '0', '2d6x100', '2d6x10'],i11to16)

i17plus = []
addRangeToTable(15,['0', '0', '2d6x1000', '8d6x100', '0'],i17plus)
addRangeToTable(40,['0', '0', '0', '1d6x1000', '1d6x100'],i17plus)
addRangeToTable(45,['0', '0', '0', '1d6x1000', '2d6x100'],i17plus)

for i in range(5):
    individual.append(i0to4)
for i in range(5,11):
    individual.append(i5to10)
for i in range(11,17):
    individual.append(i11to16)
for i in range(17,25):
    individual.append(i17plus)
    
hoard = []

v0to4 = []
for i in range(1,7):
    v0to4.append({"art":"0", "gems":"0","magic":"0d0x0"})
for i in range(7,17):
    v0to4.append({"art":"0", "gems":"2d6x10","magic":"0d0x0"})
for i in range(17,27):
    v0to4.append({"art":"2d4x25", "gems":"0","magic":"0d0x0"})
for i in range(27,37):
    v0to4.append({"art":"0", "gems":"2d6x50","magic":"0d0x0"})
for i in range(37,45):
    v0to4.append({"art":"0", "gems":"2d6x10","magic":"1d6xA"})
for i in range(45,53):
    v0to4.append({"art":"2d4x25", "gems":"0","magic":"1d6xA"})
for i in range(53,61):
    v0to4.append({"art":"0", "gems":"2d6x50","magic":"1d6xA"})
for i in range(61,66):
    v0to4.append({"art":"0", "gems":"2d6x10","magic":"1d4xB"})
for i in range(66,71):
    v0to4.append({"art":"2d4x25", "gems":"0","magic":"1d4xB"})
for i in range(71,76):
    v0to4.append({"art":"0", "gems":"2d6x50","magic":"1d4xB"})
for i in range(76,79):
    v0to4.append({"art":"0", "gems":"2d6x10","magic":"1d4xC"})
for i in range(79,81):
    v0to4.append({"art":"2d4x25", "gems":"0","magic":"1d4xC"})
for i in range(81,86):
    v0to4.append({"art":"0", "gems":"2d6x50","magic":"1d4xC"})
for i in range(86,93):
    v0to4.append({"art":"2d4x25", "gems":"0","magic":"1d4xF"})
for i in range(93,98):
    v0to4.append({"art":"0", "gems":"2d6x50","magic":"1d4xF"})
for i in range(98,100):
    v0to4.append({"art":"2d4x25", "gems":"0","magic":"1d1xG"})
v0to4.append({"art":"0", "gems":"2d6x50","magic":"1d1xG"}) #100



h0to4 = {
    "coins": ['6d6x100', "3d6x100", "0", "2d6x10","0"],
    "valuables": v0to4 
    }

v5to10 = []
addRangeToTable(4,{"art":"0","gems":"0","magic":"0d0x0"},v5to10)
addRangeToTable(6,{"art":"2d4x25","gems":"0","magic":"0d0x0"},v5to10)
addRangeToTable(6,{"art":"0","gems":"3d6x50","magic":"0d0x0"},v5to10)
addRangeToTable(6,{"art":"0","gems":"3d6x100","magic":"0d0x0"},v5to10)
addRangeToTable(6,{"art":"2d4x250","gems":"","magic":"0d0x0"},v5to10)
addRangeToTable(4,{"art":"2d4x25","gems":"0","magic":"1d6xA"},v5to10)
addRangeToTable(4,{"art":"0","gems":"3d6x50","magic":"1d6xA"},v5to10)
addRangeToTable(4,{"art":"0","gems":"3d6x100","magic":"1d6xA"},v5to10)
addRangeToTable(4,{"art":"2d4x250","gems":"0","magic":"1d6xA"},v5to10)
addRangeToTable(5,{"art":"2d4x25","gems":"0","magic":"1d4xB"},v5to10)
addRangeToTable(5,{"art":"0","gems":"3d6x50","magic":"1d4xB"},v5to10)
addRangeToTable(5,{"art":"0","gems":"3d6x100","magic":"1d4xB"},v5to10)
addRangeToTable(4,{"art":"2d4x250","gems":"0","magic":"1d4xB"},v5to10)
addRangeToTable(3,{"art":"2d4x25","gems":"0","magic":"1d4xC"},v5to10)
addRangeToTable(3,{"art":"0","gems":"3d6x50","magic":"1d4xC"},v5to10)
addRangeToTable(3,{"art":"0","gems":"3d6x100","magic":"1d4xC"},v5to10)
addRangeToTable(2,{"art":"2d4x250","gems":"0","magic":"1d4xC"},v5to10)
addRangeToTable(2,{"art":"2d4x25","gems":"0","magic":"1d1xD"},v5to10)
addRangeToTable(2,{"art":"0","gems":"3d6x50","magic":"1d1xD"},v5to10)
addRangeToTable(1,{"art":"0","gems":"3d6x100","magic":"1d1xD"},v5to10)
addRangeToTable(1,{"art":"2d4x250","gems":"0","magic":"1d1xD"},v5to10)
addRangeToTable(4,{"art":"2d4x25","gems":"0","magic":"1d4xF"},v5to10)
addRangeToTable(4,{"art":"0","gems":"3d6x50","magic":"1d4xF"},v5to10)
addRangeToTable(3,{"art":"0","gems":"3d6x100","magic":"1d4xF"},v5to10)
addRangeToTable(3,{"art":"2d4x250","gems":"0","magic":"1d4xF"},v5to10)
addRangeToTable(2,{"art":"2d4x25","gems":"0","magic":"1d4xG"},v5to10)
addRangeToTable(2,{"art":"0","gems":"3d6x50","magic":"1d4xG"},v5to10)
addRangeToTable(1,{"art":"0","gems":"3d6x100","magic":"1d1xH"},v5to10)
addRangeToTable(1,{"art":"2d4x250","gems":"0","magic":"1d1xH"},v5to10)

h5to10 = {
    "coins": ['2d6x100','2d6x1000', '0', '6d6x100', '3d6x10'],
    "valuables": v5to10
}

v11to16 = []
addRangeToTable(3,{"art":"0","gems":"0","magic":"0d0x0"},v11to16)
addRangeToTable(3,{"art":"2d4x250","gems":"0","magic":"0d0x0"},v11to16)
addRangeToTable(3,{"art":"2d4x750","gems":"0","magic":"0d0x0"},v11to16)
addRangeToTable(3,{"art":"0","gems":"3d6x500","magic":"0d0x0"},v11to16)
addRangeToTable(3,{"art":"0","gems":"3d6x1000","magic":"0d0x0"},v11to16)
addRangeToTable(4,{"art":"2d4x250","gems":"0","magic":["1d4xA","1d6xB"]},v11to16)
addRangeToTable(4,{"art":"2d4x750","gems":"0","magic":["1d4xA","1d6xB"]},v11to16)
addRangeToTable(3,{"art":"0","gems":"3d6x500","magic":["1d4xA","1d6xB"]},v11to16)
addRangeToTable(3,{"art":"0","gems":"3d6x1000","magic":["1d4xA","1d6xB"]},v11to16)
addRangeToTable(6,{"art":"2d4x250","gems":"0","magic":"1d6xC"},v11to16)
addRangeToTable(5,{"art":"2d4x750","gems":"0","magic":"1d6xC"},v11to16)
addRangeToTable(5,{"art":"0","gems":"3d6x500","magic":"1d6xC"},v11to16)
addRangeToTable(5,{"art":"0","gems":"3d6x1000","magic":"1d6xC"},v11to16)
addRangeToTable(4,{"art":"2d4x250","gems":"0","magic":"1d4xD"},v11to16)
addRangeToTable(4,{"art":"2d4x750","gems":"0","magic":"1d4xD"},v11to16)
addRangeToTable(4,{"art":"0","gems":"3d6x500","magic":"1d4xD"},v11to16)
addRangeToTable(4,{"art":"0","gems":"3d6x1000","magic":"1d4xD"},v11to16)
addRangeToTable(2,{"art":"2d4x250","gems":"0","magic":"1d1xE"},v11to16)
addRangeToTable(2,{"art":"2d4x750","gems":"0","magic":"1d1xE"},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x500","magic":"1d1xE"},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x1000","magic":"1d1xE"},v11to16)
addRangeToTable(2,{"art":"2d4x250","gems":"0","magic":["1d1xF","1d4xG"]},v11to16)
addRangeToTable(2,{"art":"2d4x750","gems":"0","magic":["1d1xF","1d4xG"]},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x500","magic":["1d1xF","1d4xG"]},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x1000","magic":["1d1xF","1d4xG"]},v11to16)
addRangeToTable(3,{"art":"2d4x250","gems":"0","magic":"1d4xH"},v11to16)
addRangeToTable(3,{"art":"2d4x750","gems":"0","magic":"1d4xH"},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x500","magic":"1d4xH"},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x1000","magic":"1d4xH"},v11to16)
addRangeToTable(2,{"art":"2d4x250","gems":"0","magic":"1d1xI"},v11to16)
addRangeToTable(2,{"art":"2d4x750","gems":"0","magic":"1d1xI"},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x500","magic":"1d1xI"},v11to16)
addRangeToTable(2,{"art":"0","gems":"3d6x1000","magic":"1d1xI"},v11to16)

h11to16 = {
    "coins": ['0', '0', '0', '4d6x1000', '5d6x100'],
    "valuables": v11to16
}

v17plus = []
addRangeToTable(2,{"art":"0","gems":"0","magic":"0d0x0"},v17plus)
addRangeToTable(3,{"art":"0","gems":"3d6x1000","magic":"1d8xC"},v17plus)
addRangeToTable(3,{"art":"1d10x2500","gems":"0","magic":"1d8xC"},v17plus)
addRangeToTable(3,{"art":"1d4x7500","gems":"0","magic":"1d8xC"},v17plus)
addRangeToTable(3,{"art":"0","gems":"1d8x5000","magic":"1d8xC"},v17plus)
addRangeToTable(8,{"art":"0","gems":"3d6x1000","magic":"1d6xD"},v17plus)
addRangeToTable(8,{"art":"1d10x2500","gems":"0","magic":"1d6xD"},v17plus)
addRangeToTable(8,{"art":"1d4x7500","gems":"0","magic":"1d6xD"},v17plus)
addRangeToTable(8,{"art":"0","gems":"1d8x5000","magic":"1d6xD"},v17plus)
addRangeToTable(6,{"art":"0","gems":"3d6x1000","magic":"1d6xE"},v17plus)
addRangeToTable(6,{"art":"1d10x2500","gems":"0","magic":"1d6xE"},v17plus)
addRangeToTable(5,{"art":"1d4x7500","gems":"0","magic":"1d6xE"},v17plus)
addRangeToTable(5,{"art":"0","gems":"1d8x5000","magic":"1d6xE"},v17plus)
addRangeToTable(1,{"art":"0","gems":"3d6x1000","magic":"1d4xG"},v17plus)
addRangeToTable(1,{"art":"1d10x2500","gems":"0","magic":"1d4xG"},v17plus)
addRangeToTable(1,{"art":"1d4x7500","gems":"0","magic":"1d4xG"},v17plus)
addRangeToTable(1,{"art":"0","gems":"1d8x5000","magic":"1d4xG"},v17plus)
addRangeToTable(2,{"art":"0","gems":"3d6x1000","magic":"1d4xH"},v17plus)
addRangeToTable(2,{"art":"1d10x2500","gems":"0","magic":"1d4xH"},v17plus)
addRangeToTable(2,{"art":"1d4x7500","gems":"0","magic":"1d4xH"},v17plus)
addRangeToTable(2,{"art":"0","gems":"1d8x5000","magic":"1d4xH"},v17plus)
addRangeToTable(5,{"art":"0","gems":"3d6x1000","magic":"1d4xI"},v17plus)
addRangeToTable(5,{"art":"1d10x2500","gems":"0","magic":"1d4xI"},v17plus)
addRangeToTable(5,{"art":"1d4x7500","gems":"0","magic":"1d4xI"},v17plus)
addRangeToTable(5,{"art":"0","gems":"1d8x5000","magic":"1d4xI"},v17plus)

h17plus = {
    "coins": ['0', '0', '0', '12d6x1000', '8d6x1000'],
    "valuables": v17plus
}

for i in range(5):
    hoard.append(h0to4)
for i in range(5,11):
    hoard.append(h5to10)
for i in range(11,17):
    hoard.append(h11to16)
for i in range(17,25):
    hoard.append(h17plus)

